//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueMount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrueMount.LanguageDictionary", typeof(LanguageDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} key files/directories..
        /// </summary>
        internal static string AddKeyFiles {
            get {
                return ResourceManager.GetString("AddKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding mount options: {0}.
        /// </summary>
        internal static string AddMountOpts {
            get {
                return ResourceManager.GetString("AddMountOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been mounted as {1}:.
        /// </summary>
        internal static string BalloonVolMounted {
            get {
                return ResourceManager.GetString("BalloonVolMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Letter .
        /// </summary>
        internal static string CBoxLetter {
            get {
                return ResourceManager.GetString("CBoxLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Partition .
        /// </summary>
        internal static string CBoxPartition {
            get {
                return ResourceManager.GetString("CBoxPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check configuration, I can&apos;t work without truecrypt :(.
        /// </summary>
        internal static string CheckCfgTC {
            get {
                return ResourceManager.GetString("CheckCfgTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your configuration!.
        /// </summary>
        internal static string CheckConfig {
            get {
                return ResourceManager.GetString("CheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust your configuration, I can&apos;t go on :(.
        /// </summary>
        internal static string CheckTCConf {
            get {
                return ResourceManager.GetString("CheckTCConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container file {0} disabled, skipped..
        /// </summary>
        internal static string ConConfDisabled {
            get {
                return ResourceManager.GetString("ConConfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container file {0} enabled..
        /// </summary>
        internal static string ConConfEnabled {
            get {
                return ResourceManager.GetString("ConConfEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container file {0} found..
        /// </summary>
        internal static string ConFileFound {
            get {
                return ResourceManager.GetString("ConFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener already running..
        /// </summary>
        internal static string DevListenerIsRun {
            get {
                return ResourceManager.GetString("DevListenerIsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener not running..
        /// </summary>
        internal static string DevListenerNoRun {
            get {
                return ResourceManager.GetString("DevListenerNoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener running..
        /// </summary>
        internal static string DevListenerRun {
            get {
                return ResourceManager.GetString("DevListenerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener stopped..
        /// </summary>
        internal static string DevListenerStop {
            get {
                return ResourceManager.GetString("DevListenerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk device {0} config enabled..
        /// </summary>
        internal static string DiskConfEnabled {
            get {
                return ResourceManager.GetString("DiskConfEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk drive DeviceID: {0}.
        /// </summary>
        internal static string DiskDeviceId {
            get {
                return ResourceManager.GetString("DiskDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk drive {0} config disabled, skipped..
        /// </summary>
        internal static string DiskDriveConfDisabled {
            get {
                return ResourceManager.GetString("DiskDriveConfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk drive {0} is offline, skipped..
        /// </summary>
        internal static string DiskDriveOffline {
            get {
                return ResourceManager.GetString("DiskDriveOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk drive Path: {0}.
        /// </summary>
        internal static string DiskDrivePath {
            get {
                return ResourceManager.GetString("DiskDrivePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk drive {0} is online..
        /// </summary>
        internal static string DiskIsOnline {
            get {
                return ResourceManager.GetString("DiskIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk partition letter: {0}.
        /// </summary>
        internal static string DiskPartLetter {
            get {
                return ResourceManager.GetString("DiskPartLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded: {0}%.
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive letter: {0}.
        /// </summary>
        internal static string DriveLetter {
            get {
                return ResourceManager.GetString("DriveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please check the config!.
        /// </summary>
        internal static string ErrCheckConfig {
            get {
                return ResourceManager.GetString("ErrCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: container file {0} could not be found!.
        /// </summary>
        internal static string ErrConFileNotExists {
            get {
                return ResourceManager.GetString("ErrConFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Device Listener could not be started!.
        /// </summary>
        internal static string ErrDevListenerStart {
            get {
                return ResourceManager.GetString("ErrDevListenerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while opening the explorer!.
        /// </summary>
        internal static string ErrExplorerOpen {
            get {
                return ResourceManager.GetString("ErrExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrGeneral {
            get {
                return ResourceManager.GetString("ErrGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: drive letter {0} already in use!.
        /// </summary>
        internal static string ErrLetterInUse {
            get {
                return ResourceManager.GetString("ErrLetterInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: key device configuration incorrect/incomplete, check the settings!.
        /// </summary>
        internal static string ErrNoKeyDev {
            get {
                return ResourceManager.GetString("ErrNoKeyDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: password file {0} does not exist, skipped..
        /// </summary>
        internal static string ErrPwFileNoExist {
            get {
                return ResourceManager.GetString("ErrPwFileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: truecrypt executable not found, jobs stopped..
        /// </summary>
        internal static string ErrTCNotFound {
            get {
                return ResourceManager.GetString("ErrTCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: your path to TrueCrypt seems wrong, please check the configuration!.
        /// </summary>
        internal static string ErrTCPathWrong {
            get {
                return ResourceManager.GetString("ErrTCPathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical disk {0}:\ online..
        /// </summary>
        internal static string LogicalDiskOnline {
            get {
                return ResourceManager.GetString("LogicalDiskOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount of {0} canceled!.
        /// </summary>
        internal static string MountCanceled {
            get {
                return ResourceManager.GetString("MountCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted partitions: {0}.
        /// </summary>
        internal static string MountedPartitions {
            get {
                return ResourceManager.GetString("MountedPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string MsgDone {
            get {
                return ResourceManager.GetString("MsgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate detected.
        /// </summary>
        internal static string MsgHDevDouble {
            get {
                return ResourceManager.GetString("MsgHDevDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk already chosen.
        /// </summary>
        internal static string MsgHDiskDouble {
            get {
                return ResourceManager.GetString("MsgHDiskDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen disk offline.
        /// </summary>
        internal static string MsgHDiskOff {
            get {
                return ResourceManager.GetString("MsgHDiskOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount error.
        /// </summary>
        internal static string MsgHDiskTimeout {
            get {
                return ResourceManager.GetString("MsgHDiskTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secound start.
        /// </summary>
        internal static string MsgHInsranceInfo {
            get {
                return ResourceManager.GetString("MsgHInsranceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version found online.
        /// </summary>
        internal static string MsgHNewVersion {
            get {
                return ResourceManager.GetString("MsgHNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version.
        /// </summary>
        internal static string MsgHNoNewVersion {
            get {
                return ResourceManager.GetString("MsgHNoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password file missing.
        /// </summary>
        internal static string MsgHNoPw {
            get {
                return ResourceManager.GetString("MsgHNoPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgHNoTCSet {
            get {
                return ResourceManager.GetString("MsgHNoTCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MsgHSaved {
            get {
                return ResourceManager.GetString("MsgHSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string MsgHUDownloadFail {
            get {
                return ResourceManager.GetString("MsgHUDownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatibility problem.
        /// </summary>
        internal static string MsgHUpdateIncompatible {
            get {
                return ResourceManager.GetString("MsgHUpdateIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings unsaved.
        /// </summary>
        internal static string MsgHWarnNotSaved {
            get {
                return ResourceManager.GetString("MsgHWarnNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmount of all devices.
        /// </summary>
        internal static string MsgHWarnUmount {
            get {
                return ResourceManager.GetString("MsgHWarnUmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Key Device already exists!.
        /// </summary>
        internal static string MsgTDevDouble {
            get {
                return ResourceManager.GetString("MsgTDevDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected disk/partition already exists!.
        /// </summary>
        internal static string MsgTDiskDouble {
            get {
                return ResourceManager.GetString("MsgTDiskDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen disk seems to be offline, please reopen this dialog!.
        /// </summary>
        internal static string MsgTDiskOff {
            get {
                return ResourceManager.GetString("MsgTDiskOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mount of {0} seems seems to have not worked! Please check the log output and your settings!.
        /// </summary>
        internal static string MsgTDiskTimeout {
            get {
                return ResourceManager.GetString("MsgTDiskTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an instance of TrueMount running!.
        /// </summary>
        internal static string MsgTInsranceInfo {
            get {
                return ResourceManager.GetString("MsgTInsranceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of TrueMount is available, download and install?.
        /// </summary>
        internal static string MsgTNewVersion {
            get {
                return ResourceManager.GetString("MsgTNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version available this time..
        /// </summary>
        internal static string MsgTNoNewVersion {
            get {
                return ResourceManager.GetString("MsgTNoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a password file!.
        /// </summary>
        internal static string MsgTNoPw {
            get {
                return ResourceManager.GetString("MsgTNoPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not set a valid TrueCrypt path, TrueMount will not work!.
        /// </summary>
        internal static string MsgTNoTCSet {
            get {
                return ResourceManager.GetString("MsgTNoTCSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string MsgTSaved {
            get {
                return ResourceManager.GetString("MsgTSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating failed!.
        /// </summary>
        internal static string MsgTUpdateFail {
            get {
                return ResourceManager.GetString("MsgTUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be a compatibility issue, please download and install the latest version by hand!.
        /// </summary>
        internal static string MsgTUpdateIncompatible {
            get {
                return ResourceManager.GetString("MsgTUpdateIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not save your changed settings, really close?.
        /// </summary>
        internal static string MsgTWarnNotSaved {
            get {
                return ResourceManager.GetString("MsgTWarnNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to unmount all of your encrypted devices, data loss may be possible! Continue?.
        /// </summary>
        internal static string MsgTWarnUmount {
            get {
                return ResourceManager.GetString("MsgTWarnUmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New volume mounted.
        /// </summary>
        internal static string NewVolumeMounted {
            get {
                return ResourceManager.GetString("NewVolumeMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: No key files set..
        /// </summary>
        internal static string NoKeyFiles {
            get {
                return ResourceManager.GetString("NoKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: No mount options set..
        /// </summary>
        internal static string NoMountOpts {
            get {
                return ResourceManager.GetString("NoMountOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}:\ in explorer..
        /// </summary>
        internal static string OpenExplorer {
            get {
                return ResourceManager.GetString("OpenExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: No password set..
        /// </summary>
        internal static string PasswordEmptyOk {
            get {
                return ResourceManager.GetString("PasswordEmptyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password file: {0}.
        /// </summary>
        internal static string PasswordFile {
            get {
                return ResourceManager.GetString("PasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password read successfully..
        /// </summary>
        internal static string PasswordReadOk {
            get {
                return ResourceManager.GetString("PasswordReadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Device {0} online..
        /// </summary>
        internal static string PDevOnline {
            get {
                return ResourceManager.GetString("PDevOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started..
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart in config disabled, Listener not started..
        /// </summary>
        internal static string SAutoDi {
            get {
                return ResourceManager.GetString("SAutoDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Autostart enabled, starting work..
        /// </summary>
        internal static string SAutoEn {
            get {
                return ResourceManager.GetString("SAutoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new container file..
        /// </summary>
        internal static string SearchConFile {
            get {
                return ResourceManager.GetString("SearchConFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for local disk..
        /// </summary>
        internal static string SearchDiskLocal {
            get {
                return ResourceManager.GetString("SearchDiskLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Device Listener..
        /// </summary>
        internal static string StartDevListener {
            get {
                return ResourceManager.GetString("StartDevListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process..
        /// </summary>
        internal static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping device listener..
        /// </summary>
        internal static string StopDevListener {
            get {
                return ResourceManager.GetString("StopDevListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument line: {0}.
        /// </summary>
        internal static string TCArgumentLine {
            get {
                return ResourceManager.GetString("TCArgumentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueCrypt path: {0}.
        /// </summary>
        internal static string TCPath {
            get {
                return ResourceManager.GetString("TCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmounting all LogicalDisks..
        /// </summary>
        internal static string UnmountAll {
            get {
                return ResourceManager.GetString("UnmountAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New USB Device found..
        /// </summary>
        internal static string USBFound {
            get {
                return ResourceManager.GetString("USBFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device is not the password device, waiting..
        /// </summary>
        internal static string USBNotPw {
            get {
                return ResourceManager.GetString("USBNotPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device removed..
        /// </summary>
        internal static string USBRemoved {
            get {
                return ResourceManager.GetString("USBRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device to come up....
        /// </summary>
        internal static string WaitDevLaunch {
            get {
                return ResourceManager.GetString("WaitDevLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        internal static string WarnGeneral {
            get {
                return ResourceManager.GetString("WarnGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no disks found in configuration, check the settings!.
        /// </summary>
        internal static string WarnNoDisks {
            get {
                return ResourceManager.GetString("WarnNoDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no TrueCrypt configuration switch set, program window may show up!.
        /// </summary>
        internal static string WarnTCArgs {
            get {
                return ResourceManager.GetString("WarnTCArgs", resourceCulture);
            }
        }
    }
}
