//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueMount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrueMount.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} key files/directories....
        /// </summary>
        internal static string AddKeyFiles {
            get {
                return ResourceManager.GetString("AddKeyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding mount options: {0}.
        /// </summary>
        internal static string AddMountOpts {
            get {
                return ResourceManager.GetString("AddMountOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check configuration, I can&apos;t work without truecrypt :(.
        /// </summary>
        internal static string CheckCfgTC {
            get {
                return ResourceManager.GetString("CheckCfgTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your configuration!.
        /// </summary>
        internal static string CheckConfig {
            get {
                return ResourceManager.GetString("CheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust your configuration, I can&apos;t go on :(.
        /// </summary>
        internal static string CheckTCConf {
            get {
                return ResourceManager.GetString("CheckTCConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener already running..
        /// </summary>
        internal static string DevListenerIsRun {
            get {
                return ResourceManager.GetString("DevListenerIsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener not running..
        /// </summary>
        internal static string DevListenerNoRun {
            get {
                return ResourceManager.GetString("DevListenerNoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener running..
        /// </summary>
        internal static string DevListenerRun {
            get {
                return ResourceManager.GetString("DevListenerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Listener stopped..
        /// </summary>
        internal static string DevListenerStop {
            get {
                return ResourceManager.GetString("DevListenerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDevice {0} config enabled..
        /// </summary>
        internal static string DiskConfEnabled {
            get {
                return ResourceManager.GetString("DiskConfEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive DeviceID: {0}.
        /// </summary>
        internal static string DiskDeviceId {
            get {
                return ResourceManager.GetString("DiskDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive {0} config disabled, skipping....
        /// </summary>
        internal static string DiskDriveConfDisabled {
            get {
                return ResourceManager.GetString("DiskDriveConfDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive {0} is offline, skipping....
        /// </summary>
        internal static string DiskDriveOffline {
            get {
                return ResourceManager.GetString("DiskDriveOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive Path: {0}.
        /// </summary>
        internal static string DiskDrivePath {
            get {
                return ResourceManager.GetString("DiskDrivePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive {0} is online..
        /// </summary>
        internal static string DiskIsOnline {
            get {
                return ResourceManager.GetString("DiskIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskPartition letter: {0}.
        /// </summary>
        internal static string DiskPartLetter {
            get {
                return ResourceManager.GetString("DiskPartLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please check the config!.
        /// </summary>
        internal static string ErrCheckConfig {
            get {
                return ResourceManager.GetString("ErrCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Device Listener could not be started!.
        /// </summary>
        internal static string ErrDevListenerStart {
            get {
                return ResourceManager.GetString("ErrDevListenerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while opening the explorer!.
        /// </summary>
        internal static string ErrExplorerOpen {
            get {
                return ResourceManager.GetString("ErrExplorerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrGeneral {
            get {
                return ResourceManager.GetString("ErrGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: key device configuration incorrect/incomplete, check the settings!.
        /// </summary>
        internal static string ErrNoKeyDev {
            get {
                return ResourceManager.GetString("ErrNoKeyDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: password file {0} does not exist, skipping....
        /// </summary>
        internal static string ErrPwFileNoExist {
            get {
                return ResourceManager.GetString("ErrPwFileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: truecrypt executable not found, stopping jobs....
        /// </summary>
        internal static string ErrTCNotFound {
            get {
                return ResourceManager.GetString("ErrTCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: your path to TrueCrypt seems wrong, please check the configuration!.
        /// </summary>
        internal static string ErrTCPathWrong {
            get {
                return ResourceManager.GetString("ErrTCPathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogicalDisk {0}:\ online..
        /// </summary>
        internal static string LogicalDiskOnline {
            get {
                return ResourceManager.GetString("LogicalDiskOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted partitions: {0}.
        /// </summary>
        internal static string MountedPartitions {
            get {
                return ResourceManager.GetString("MountedPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string MsgDone {
            get {
                return ResourceManager.GetString("MsgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mount options set, continuing....
        /// </summary>
        internal static string NoMountOpts {
            get {
                return ResourceManager.GetString("NoMountOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}:\ in explorer....
        /// </summary>
        internal static string OpenExplorer {
            get {
                return ResourceManager.GetString("OpenExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskPartition {0} config enabled..
        /// </summary>
        internal static string PartConfEnabled {
            get {
                return ResourceManager.GetString("PartConfEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password file: {0}.
        /// </summary>
        internal static string PasswordFile {
            get {
                return ResourceManager.GetString("PasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password read successfully..
        /// </summary>
        internal static string PasswordReadOk {
            get {
                return ResourceManager.GetString("PasswordReadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Device {0} online..
        /// </summary>
        internal static string PDevOnline {
            get {
                return ResourceManager.GetString("PDevOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started..
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart in config disabled, Listener not started..
        /// </summary>
        internal static string SAutoDi {
            get {
                return ResourceManager.GetString("SAutoDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Autostart enabled, starting work....
        /// </summary>
        internal static string SAutoEn {
            get {
                return ResourceManager.GetString("SAutoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for local disk....
        /// </summary>
        internal static string SearchDiskLocal {
            get {
                return ResourceManager.GetString("SearchDiskLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Device Listener....
        /// </summary>
        internal static string StartDevListener {
            get {
                return ResourceManager.GetString("StartDevListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process....
        /// </summary>
        internal static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping device listener....
        /// </summary>
        internal static string StopDevListener {
            get {
                return ResourceManager.GetString("StopDevListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument line: {0}.
        /// </summary>
        internal static string TCArgumentLine {
            get {
                return ResourceManager.GetString("TCArgumentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueCrypt path: {0}.
        /// </summary>
        internal static string TCPath {
            get {
                return ResourceManager.GetString("TCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmounting all LogicalDisks....
        /// </summary>
        internal static string UnmountAll {
            get {
                return ResourceManager.GetString("UnmountAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New USB Device found..
        /// </summary>
        internal static string USBFound {
            get {
                return ResourceManager.GetString("USBFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device is not the password device, waiting....
        /// </summary>
        internal static string USBNotPw {
            get {
                return ResourceManager.GetString("USBNotPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device removed..
        /// </summary>
        internal static string USBRemoved {
            get {
                return ResourceManager.GetString("USBRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device to come up....
        /// </summary>
        internal static string WaitDevLaunch {
            get {
                return ResourceManager.GetString("WaitDevLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        internal static string WarnGeneral {
            get {
                return ResourceManager.GetString("WarnGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: DiskPartition letter {0} is already in use, skipping....
        /// </summary>
        internal static string WarnLetterInUse {
            get {
                return ResourceManager.GetString("WarnLetterInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no disks found in configuration, check the settings!.
        /// </summary>
        internal static string WarnNoDisks {
            get {
                return ResourceManager.GetString("WarnNoDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: no TrueCrypt configuration switch set, program window may show up!.
        /// </summary>
        internal static string WarnTCArgs {
            get {
                return ResourceManager.GetString("WarnTCArgs", resourceCulture);
            }
        }
    }
}
